// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w9YkCMoNAxdUdLu1fVbgUv
// Component: JXOduyYvIR

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MovieItem from "../../MovieItem"; // plasmic-import: Z1TaGzJ1L3/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_the_shoppies.module.css"; // plasmic-import: w9YkCMoNAxdUdLu1fVbgUv/projectcss
import sty from "./PlasmicNominations.module.css"; // plasmic-import: JXOduyYvIR/css

export type PlasmicNominations__VariantMembers = {};
export type PlasmicNominations__VariantsArgs = {};
type VariantPropType = keyof PlasmicNominations__VariantsArgs;
export const PlasmicNominations__VariantProps = new Array<VariantPropType>();

export type PlasmicNominations__ArgsType = {};
type ArgPropType = keyof PlasmicNominations__ArgsType;
export const PlasmicNominations__ArgProps = new Array<ArgPropType>();

export type PlasmicNominations__OverridesType = {
  root?: p.Flex<"div">;
  h2?: p.Flex<"h2">;
};

export interface DefaultNominationsProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicNominations__RenderFunc(props: {
  variants: PlasmicNominations__VariantsArgs;
  args: PlasmicNominations__ArgsType;
  overrides: PlasmicNominations__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <h2
        data-plasmic-name={"h2"}
        data-plasmic-override={overrides.h2}
        className={classNames(
          projectcss.all,
          projectcss.h2,
          projectcss.__wab_text,
          sty.h2
        )}
      >
        {"Your nominations"}
      </h2>
      <MovieItem
        className={classNames("__wab_instance", sty.movieItem___0U8PP)}
        deleteIcon={"withDeleteIcon" as const}
      />

      <MovieItem
        className={classNames("__wab_instance", sty.movieItem__ym8Xg)}
        deleteIcon={"withDeleteIcon" as const}
      >
        {"Murder Mystery"}
      </MovieItem>
      <MovieItem
        className={classNames("__wab_instance", sty.movieItem__feejS)}
        deleteIcon={"withDeleteIcon" as const}
      >
        {"Hirokin: The Last Samurai"}
      </MovieItem>
      <MovieItem
        className={classNames("__wab_instance", sty.movieItem__dimPf)}
        deleteIcon={"withDeleteIcon" as const}
      >
        {"Rough Diamonds"}
      </MovieItem>
      <MovieItem
        className={classNames("__wab_instance", sty.movieItem__sbzYn)}
        deleteIcon={"withDeleteIcon" as const}
      >
        {"Welcome to Eden"}
      </MovieItem>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNominations__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNominations__VariantsArgs;
    args?: PlasmicNominations__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNominations__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNominations__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNominations__ArgProps,
          internalVariantPropNames: PlasmicNominations__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNominations__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNominations";
  } else {
    func.displayName = `PlasmicNominations.${nodeName}`;
  }
  return func;
}

export const PlasmicNominations = Object.assign(
  // Top-level PlasmicNominations renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicNominations
    internalVariantProps: PlasmicNominations__VariantProps,
    internalArgProps: PlasmicNominations__ArgProps
  }
);

export default PlasmicNominations;
/* prettier-ignore-end */
